
import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { Custom, Providers } from "./Provider";
import GlobalProvider from "@/provider/GlobalProvider";
import { Toaster } from "react-hot-toast";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Online-Ecomerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <GlobalProvider>
            <Custom>{children}</Custom>
            <Toaster position="top-center" reverseOrder={false} />
          </GlobalProvider>
        </Providers>
      </body>
    </html>
  );
}
